explosion:
  strength: 1.25
  y: 1.1
  distance: 2.0
  far-strength: 0.7
  far-y: 0.8

fireball:
  speed: 1.5
  particle: "FLAME"
  particle-count: 10

team-protection-enabled: true

# Players will not receive any damage from fall.
force-disable-entity-fall-damage: false

excluded-from-explode-blocks:
  - "ENDER_STONE"
  - "WOOD"

cooldown-seconds: 0.8
cooldown-message: "&cFireball cooldown: &e$cooldown seconds"